### ISSUE TITLE
pilz_command_planner: Rviz Plugin - Movement not possible

### ISSUE THREAD

**Issue by hslusarek** [PilzDE/pilz_industrial_motion#128]
### Commit (Stand: 19.03.2019):
- kinetic-devel
- pilz_industrial_motion - Version: 0.3.6-0
- pilz_robots -  Version: 0.4.7-0
- prbt_grippers - Version: 0.0.1-0

### Steps to reproduce
Launch real robot via:  
```roslaunch prbt_moveit_config moveit_planning_execution.launch sim:=false pipeline:=pilz_command_planner```  
In Rviz perform the following steps:
1. Select Ptp command.
2. Choose position to move to.
3. Push "Plan and Execute" button and wait for robot to complete motion.
4. If "Plan and Execute" button is active, after motion is finished, go back to step 2.

### Expected behavior
After motion is finished, it should be possible to plan and execute a new motion.

### Observed behavior
For some reason sometimes the "Plan and Execute" button remains deactivated. Maybe the Pluging still waits for the motion to finish and has not received the finish signal. On the same day but maybe not in this context I also had problems with a statement like ```PATH_TOLERANCE_VIOLATED```. Maybe it is related? I normally resolved my problems by restarting ROS. The I was often able to again perform one or two Ptp movements until the problem reappeared.

**Comment by hslusarek** [comment]
- Bug **not** reproducible with commits (Stand: 26.04.19):
  - pilz_industrial_motion: 3c99424bfe4de8f289d138ef5e0038b96b69df90
  - pilz_robots: a0d4fda
  - prbt_support: 31f9f169f82839512fc4c376104e6bd09741a1cf
  - Firmeware: "100 Build:11158 Date:2018-06-07 16:49:55%"

- Bug also not reproducible with:
ros-kinetic-prbt-gazebo is already the newest version (0.4.7-0xenial-20190320-230328-0800).
ros-kinetic-prbt-grippers is already the newest version (0.0.2-0xenial-20190401-162607-0800).
ros-kinetic-prbt-hardware-support is already the newest version (0.4.7-0xenial-20190320-133544-0800).
ros-kinetic-prbt-ikfast-manipulator-plugin is already the newest version (0.4.7-0xenial-20190320-203437-0800).
ros-kinetic-prbt-moveit-config is already the newest version (0.4.7-0xenial-20190320-230112-0800).
ros-kinetic-prbt-pg70-support is already the newest version (0.0.2-0xenial-20190401-162520-0800).
ros-kinetic-prbt-support is already the newest version (0.4.7-0xenial-20190320-213140-0800).

**Comment by hslusarek** [comment]
- [ ] TODO: Determine Firmeware version of robot on which bug occured

**Comment by hslusarek** [comment]
Bug could **not** be reproduced with:
- kinetic
- pilz_industrial_motion - Version: 0.3.6-0
- pilz_robots - Version: 0.4.7-0
- prbt_grippers - Version: 0.0.2-0
- Firmeware: 101 Build:11345 Date:2018-12-17 07:33:06\x15\x02\0

**Comment by martiniil** [comment]
@hslusarek Close?

**Comment by hslusarek** [comment]
Yes. Close because not reproducible.
