### ISSUE TITLE
Synchronize of previously working velocity profile fails

### ISSUE THREAD

**Issue by hslusarek** [PilzDE/pilz_industrial_motion#136]
### Commit
I rebased against kinetic devel. My current commit is: 6dfd8a917c3fc941110450263f900f63cafb803b. Now some of the python tests do not work (e.g. tst_sequence_with_gripper and tst_api_execution_stop). On the console I see that the velocity profiles between certain axis cannot be synchronized.
I found this problem on kinetic-devel (6e3da7394a3f9c02680d5d430c121fd5af283922,  see also [here on Travis](https://api.travis-ci.org/v3/job/515644840/log.txt)) and melodic-devel (7f8ad2bace5765b539b1b076572ead31fbe1d24f, see also [here on Travis](https://api.travis-ci.org/v3/job/516490207/log.txt))

@martiniil Do you might know why previously working tests suddenly fail?

**Comment by martiniil** [comment]
This bug was hidden because a failure of `VelocityProfile_ATrap::SetProfileAllDurations` had no effect before 4e63042f8314f7c69f441b15ee0f71d3b3d68561 (return value was ignored).
