### ISSUE TITLE
CommandListManager should explicitly check for end-effector/missing solver

### ISSUE THREAD

**Issue by martiniil** [PilzDE/pilz_industrial_motion#144]
### Commit
ae27c43c3fb33c4970492580ee3a81d6c3426775

Currently, we throw if the group for blending is an end-effector or has no solver:
https://github.com/PilzDE/pilz_industrial_motion/blob/ae27c43c3fb33c4970492580ee3a81d6c3426775/pilz_trajectory_generation/include/pilz_trajectory_generation/tip_frame_getter.h#L22

I think it would be more "transparent" to add a check directly to the comand_list_manager.

**Comment by hslusarek** [comment]
I closed the issue after a discussion with martiniil. The idea is to perform checks when I actually need the information and not beforehand. In other words, the guideline is perform the check at the lowest possible level.
