### ISSUE TITLE
Guessing parameters

### ISSUE THREAD

**Issue by JonathanGruner** [PilzDE/pilz_industrial_motion#154]
I have a problem with programming a application effective, because of guessing parameters if the program is not able to execute the move commands. I would request a feature to make programming more usable for industries if the parameters are not important for me but for the program, than the program should use a possible parameter on his own.

i.e.: LIN movements--> velocity. If i don't give any velocity parameter than i dont care about velocity, the robot should drive as fast as he can.

It would help too if the program could recommend me a working parameter, even this is way faster as to step yourself to the right parameter, because in most cases I really don't care about them.

This includes:
- LIN-->velocity, acceleration
- Sequence --> Blend radius, acceleration

![IMG_0150](https://user-images.githubusercontent.com/44464164/56945037-e3b89e80-6b25-11e9-899a-62ffc5883018.JPG)
![IMG_0151](https://user-images.githubusercontent.com/44464164/56945061-021e9a00-6b26-11e9-8505-4da2ce1fb12c.JPG)

**Comment by hslusarek** [comment]
@dbakovic What do you think?

**Comment by dbakovic** [comment]
@JonathanGruner Thank you for your suggestion. We have it already on our todo list. Due to tasks of higher priority it will take a while before we start with the implementation.
