### ISSUE TITLE
Frankaemika panda command planning integration tests fail

### ISSUE THREAD

**Issue by hslusarek** [PilzDE/pilz_industrial_motion#16]
Currently, the Travis builds fail because the Frankaemika panda command_planning integration tests fail (see [here](https://travis-ci.org/PilzDE/pilz_industrial_motion/jobs/454918905)). 

We tried different things and discovered that the Frankaemika panda package has changed. Currently we believe that the collision model of the Frankaemika robot has changed. In our tests the panda robot starts at a position which seems to already have a collision between link 5 and 7 of the panda robot.

For now, we deactivated the command_planning integration tests for the panda robot (see 19f4eb911559362e01fe6b408e7500d9042df3e5). This Issue should fix the problems with the panda integration tests and re-activate the command_planning integration tests for the panda robot.

**Comment by martiniil** [comment]
The following commit introduces the failure on our side. Just an enabling of the collision between links 5 and 7.
https://github.com/ros-planning/panda_moveit_config/commit/ccf7720d36d0df7f1c8db2d6911e18457bca073e

Altering the start position should fix this.
