### ISSUE TITLE
Joint Goal does not accept tuple

### ISSUE THREAD

**Issue by rfeistenauer** [PilzDE/pilz_industrial_motion#160]
### Steps to reproduce
How can the issue/bug be reproduced?
`r.move(goal=(0, 0, 0, 0, 0, 0))`

### Expected behavior
same as with list

### Observed behavior
does not recognize goal

**Comment by agutenkunst** [comment]
@rfeistenauer Please use the issue template on future issues.

PR welcome. But please remember to add docu/tests.

**Comment by jschleicher** [comment]
Fixed in #237.
