### ISSUE TITLE
final kinetic->melodic merge _after_ changing the default branch

### ISSUE THREAD

**Issue by jschleicher** [PilzDE/pilz_industrial_motion#165]
@jschleicher I would rather do a final kinetic->melodic merge _after_ merging this PR.

_Originally posted by @martiniil in https://github.com/PilzDE/pilz_industrial_motion/pull/150#issuecomment-484377930_

**Comment by jschleicher** [comment]
Imho the kinetic->melodic merge should hapen asap, before any new melodic PRs to keep merge conflicts managable.
#161 shows, that the current state is confusing.

**Comment by martiniil** [comment]
I prepared the merge here: #168
