### ISSUE TITLE
Enhance docu for brake test

### ISSUE THREAD

**Issue by ct2034** [PilzDE/pilz_industrial_motion#188]
The api docu of brake test should be enhanced

**Comment by ct2034** [comment]
The api docu of brake test should be enhanced

**Comment by jschleicher** [comment]
http://docs.ros.org/melodic/api/pilz_robot_programming/html/index.html#pilz_robot_programming.robot.Robot.execute_brake_test looks good. Please re-open, if you think there are still issues.
