### ISSUE TITLE
Integration with other robot

### ISSUE THREAD

**Issue by dabhijeet** [PilzDE/pilz_industrial_motion#210]
Hello,

I was trying to integrate pilz_industrial_motion with our package. For that we changed the below parameters according to our robot

_DEFAULT_PLANNING_GROUP = "arm"
_DEFAULT_TARGET_LINK = "tcp"
_DEFAULT_GRIPPER_PLANNING_GROUP = "gripper"
_DEFAULT_BASE_LINK = "Link_1"

Also we commented the exceptions.py so that there won't be error related to BrakeTestErrorCodes. 

But when we run 
rosrun pilz_robot_programming demo_program.py
it is waiting for the action server (**Waiting for connection to action server sequence_move_group...**) 

I am attaching the rqt_graph result. Please let me know what mistake i did in the process..

Thank you in advance

![action error](https://user-images.githubusercontent.com/44795831/65769633-a5b1bc00-e151-11e9-8d37-3fb78cb19acb.png)

**Comment by martiniil** [comment]
When you start the move_group you have to specify our planner `pilz::CommandPlanner` and the capabilities `pilz_trajectory_generation/MoveGroupSequenceAction` and `pilz_trajectory_generation/MoveGroupSequenceService`.

See https://github.com/PilzDE/pilz_industrial_motion/blob/melodic-devel/pilz_trajectory_generation/README.md#using-the-command-planner

The `move_group.launch` for our robot shows how this is done:
https://github.com/PilzDE/pilz_robots/blob/melodic-devel/prbt_moveit_config/launch/move_group.launch

**Comment by dabhijeet** [comment]
Thanks....
Now it is working fine..

**Comment by logicraju** [comment]
> Thanks.... Now it is working fine..

How did you solve it ? Regards
