### ISSUE TITLE
Merge into ros-planning/moveit repo?

### ISSUE THREAD

**Issue by davetcoleman** [PilzDE/pilz_industrial_motion#228]
I think these new planners are really powerful, and the test coverage even more impressive. Is there interest in adding these planners to [moveit_planners](https://github.com/ros-planning/moveit/tree/master/moveit_planners/) alongside OMPL, SBPL, CHOMP, and TrajOpt?

**Comment by ct2034** [comment]
Thanks for the suggestion @davetcoleman! As I said in Macau, this sounds great to me but we have to discuss this internally and will get back to you next week.

**Comment by jschleicher** [comment]
See ros-planning/moveit#1893.
Closing here.
