### ISSUE TITLE
pilz_robot_programming documentation of private classes is missing

### ISSUE THREAD

**Issue by agutenkunst** [PilzDE/pilz_industrial_motion#241]
### Commit
e11efa059f44bb3402770cae2ab56d7b46dccd48
Note that: #239 is needed for proper documentation generation

### Description
If a class has a underscore prefix no documentation is generated for it.
Thus e.g. `_BaseCmd` has no documentation generated.
This can cause things like #238 

Maybe @tfoote or @jobleier have any input on this?

**Comment by agutenkunst** [comment]
I am not able to figure out some decent way and therefore would suggest a rename `_BaseCmd` to `BaseCmd` @hslusarek your opinion?

**Comment by hslusarek** [comment]
> I am not able to figure out some decent way and therefore would suggest a rename `_BaseCmd` to `BaseCmd` @hslusarek your opinion?

I think your suggestion to rename `_BaseCmd` to `BaseCmd` is ok. Maybe at one point or another an external programmer wants to add to our commands and then this change might also come in handy.
