### ISSUE TITLE
Make master branch buildable under kinetic

### ISSUE THREAD

**Issue by ct2034** [PilzDE/pilz_industrial_motion#267]
In the moveit merge, test are failing under kinetic
https://travis-ci.org/github/ros-planning/moveit/jobs/681443052#L10828

**Comment by jschleicher** [comment]
Does that help? https://github.com/ros-planning/moveit/pull/1893#issuecomment-622144021

**Comment by ct2034** [comment]
At the moment I think it is our tests that are failing but it is not possible to get information out of Travis to see why they are failing exactly, just that they are producing no test results. I will try to reproduce this with a kinetic setup

**Comment by jschleicher** [comment]
maybe our tests, maybe not: https://github.com/ros-planning/moveit/issues/2042

**Comment by jschleicher** [comment]
For instructions to run kinetic in a docker container see https://github.com/ros-planning/moveit/pull/2031#issuecomment-622164655.

Maybe the kinematics solver is missing: prbt_ikfast_manipulator_plugin probably should be added to the build (e.g. via moveit.rosinstall or moveit_resources?), to match the SONAME version of moveit core / master.

**Comment by jschleicher** [comment]
kinetic build is no longer relevant.
