### ISSUE TITLE
Move files from repo pilz_teach to new package in pilz_industrial_motion

### ISSUE THREAD

**Issue by hslusarek** [PilzDE/pilz_industrial_motion#271]
For deletion of files in `pilz_teach` see PR: PilzDe/pilz_teach#59
For new package see PR: PilzDe/pilz_industrial_motion#282

Move the following files:
- [x] [ros_message_serializer.py](https://github.com/PilzDE/pilz_teach/blob/melodic-devel/pilz_teleoperation/src/pilz_teleoperation/ros_message_serializer.py) 
- [x] [store_current_pose.py](https://github.com/PilzDE/pilz_teach/blob/melodic-devel/pilz_teleoperation/scripts/store_current_pose.py)
- [x] [pose_visualisation_node.py](https://github.com/PilzDE/pilz_teach/blob/melodic-devel/pilz_teleoperation/scripts/pose_visualisation_node.py)
- [x] [test_pose_visualisation.py](https://github.com/PilzDE/pilz_teach/blob/melodic-devel/pilz_teleoperation/test/unittests/test_pose_visualisation.py)
- [x] [test_ros_message_serializer.py](https://github.com/PilzDE/pilz_teach/blob/melodic-devel/pilz_teleoperation/test/unittests/test_ros_message_serializer.py)
- [x] [README.md chapter "Store Points"](https://github.com/PilzDE/pilz_teach/blob/melodic-devel/pilz_teleoperation/README.md#store-points)
- [x] Delete the moved files from the repository `pilz_teach`
- [x] Delete in README.md "Store Points" chapter/ make comment that store points feature was moved.
- [x] Investigate problem with store point visualization in newly created package

**Comment by hslusarek** [comment]
@rfeistenauer What about [pose_file_tf_publisher.py](https://github.com/PilzDE/pilz_teach/blob/melodic-devel/pilz_teleoperation/src/pilz_teleoperation/pose_file_tf_publisher.py)? We also moved this file because it is only used in the already moved files.

**Comment by rfeistenauer** [comment]
Yes, it should stay with the store points feature.
