### ISSUE TITLE
Integrate PyTest coverage in Travis-CI 

### ISSUE THREAD

**Issue by hslusarek** [PilzDE/pilz_industrial_motion#275]
Currently the coverage can only be run manually via [run-coverage.sh](https://github.com/PilzDE/pilz_teach/blob/melodic-devel/pilz_teleoperation/test/unittests/run-coverage.sh). In this task the coverage has to be included into the CI.

**Comment by jschleicher** [comment]
Duplicate of #289. Closing here.
