### ISSUE TITLE
Define new API for storage of position

### ISSUE THREAD

**Issue by hslusarek** [PilzDE/pilz_industrial_motion#276]
## Example
1. terminal:
```
roslaunch teach_positions.launch filename:=points.py

$ > Waiting to store points. Call save_position service or call save_joints service to append the current robot state to the file.
```

2. terminal:
```
$ rosservice call save_position

$ rosservice call save_joints (name:=pick_pose)
```

**Comment by martiniil** [comment]
If the `name`-argument is not specified, the teached positions/joints are named with a counter.

**Comment by martiniil** [comment]
A file is created in the current directory/relative/absolute path. If the file already exists, it is overwritten.

**Comment by martiniil** [comment]
@jschleicher Should a gripper joint be included in the stored joints?
