### ISSUE TITLE
Add prbt_moveit_config to moveit_resources

### ISSUE THREAD

**Issue by SansoneG** [PilzDE/pilz_industrial_motion#286]
Please use this branch: https://github.com/PilzDE/moveit/tree/pilz_planner_merge-moveit_resources

- [ ] Add to https://github.com/ros-planning/moveit_resources
- [ ] Adapt https://github.com/ros-planning/moveit/pull/1893 to reference new moveit_resource package

**Comment by jschleicher** [comment]
Done - PR 43 pending.
