### ISSUE TITLE
Set controller configuration execution mode to "last point" -> hopefully half the build time

### ISSUE THREAD

**Issue by ct2034** [PilzDE/pilz_industrial_motion#288]
Use this feature http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/fake_controller_manager/fake_controller_manager_tutorial.html

Please use this branch: https://github.com/PilzDE/moveit/tree/pilz_planner_merge-moveit_resources

- [ ] Decide which tests this makes sense for
- [ ] Decide how to configure `type: interpolate | via points | last point`
- [ ] Check correctness of tests
- [ ] Implement in https://github.com/ros-planning/moveit/pull/1893

**Comment by jschleicher** [comment]
implemented for integrationtest_sequence_action_capability* which is the only test case, that actually moves the robot. See \#1893.
