### ISSUE TITLE
Complete DOD: Store single position

### ISSUE THREAD

**Issue by martiniil** [PilzDE/pilz_industrial_motion#292]
## Documentation
* [x] Public api function documentation (sphinx/doxygen are [autogenerated online](http://docs.ros.org/melodic/api/pilz_robots/html/) with diagrams embedded)
* [x] ~[Tutorials](https://wiki.ros.org/pilz_robots/Tutorials/)~ new PBI?
* [x] Overview on [ROS wiki](https://wiki.ros.org/pilz_robots)
Insert at 4.1
```
'''pilz_store_positions''' allows storing one position for reuse by [[pilz_robot_programming]]
```
* [x] Package Readme ([example pilz_robots](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/README.md))
* [x] Good commit messages ([some tips](https://dev.to/jacobherrington/how-to-write-useful-commit-messages-my-commit-message-template-20n9
))
* [x] CHANGELOG.rst updated
* [x] Copyright headers

## Reviews
* [ ] ~Soft- and hardware architecture (diagrams and description)~ (copied from pilz_teach)
* [x] Test review (test plan and individual test cases)
* [x] Documentation review
* [x] Code (coding rules, style guide)

## Quality
* [x] CI pass:
The travis job (for example in [pilz_robots](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/.travis.yml)) checks full code coverage, successful test execution and code formatting.

## Demo
* [x] Example program / snippet prepared ([example at pilz_robot_programming](See Readme))
* [ ] Ready for sprint review

## Release planning
* [ ] When is the new feature released? * After the feature is done. *
* [x] ~Which dependent packages do have to be released simultaneously?~

## Cleanup
* [x] [Squash-Merge](https://github.blog/2016-04-01-squash-your-commits/)
* [x] Delete feature branch

**Comment by agutenkunst** [comment]
Waiting for #291
