### ISSUE TITLE
User can disable speed override via Python API

### ISSUE THREAD

**Issue by martiniil** [PilzDE/pilz_industrial_motion#293]
### Commit
831fce5c230a07c54e7db9f770adc8f436e1d533

### Steps to reproduce
Start real robot. Switch into operation mode T1.
Command a movement (e.g. PTP) through the Python API. Choose velocity scale `10`.

### Expected behavior
No movement should be executed. An error message should be displayed, like e.g. "Invalid velocity scale"

### Observed behavior
**(Still to be validated with the real robot)**
In operation mode T1 a speed override of `0.1` leads to a final scaling of `10*0.1=1`. Subsequently, a movement with scaling `1` is executed.

**Comment by agutenkunst** [comment]
imho velocity scale > 1 should not be allowed

> The value is given in percentage of the maximal velocity of an axis and has to be in range: (0,1].

See http://docs.ros.org/melodic/api/pilz_robot_programming/html/#move
