### ISSUE TITLE
unittest_trajectory_blender_transition_window fails in moveit merge

### ISSUE THREAD

**Issue by ct2034** [PilzDE/pilz_industrial_motion#300]
See https://travis-ci.org/github/PilzDE/moveit/builds/692126846

What I tried so far:
* No reproducible when building with catkin locally
* Reproducible when running in moveit_ci locally with:
```
export ROS_DISTRO=melodic
export ROS_REPO=ros
export TRAVIS_BRANCH=master
# export TEST=clang-tidy-fix
export TEST_BLACKLIST="moveit_jog_arm \
moveit_setup_assistant \
moveit_ros_planning_interface \
moveit_ros_robot_interaction \
moveit_core \
moveit_ros_perception \
moveit_kinematics \
moveit_ros_visualization \
moveit_commander"
export UPSTREAM_WORKSPACE=moveit.rosinstall
export WARNINGS_OK=false
export CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls"
```

Tipp: When this docker image is finished running (assuming the test also failed there, find its name with `docker ps -a`, it will probably be the latest one, probably on the top of the list), you can save the final state of the docker container as new image with `docker commit [finished_container_name_from_moveit_ci] [new_image_name]` and then start a terminal in this one with `docker start -it [new_image_name] bash` to explore what went wrong.

**Comment by jschleicher** [comment]
done
