### ISSUE TITLE
Collision avoidance with Pilz industrial Motion Planner

### ISSUE THREAD

**Issue by anshulpaigwar** [PilzDE/pilz_industrial_motion#329]
Does Pilz Industrial Motion Planner supports collision avoidance using planning_scene framework and CollisionObject msg??

**Comment by jschleicher** [comment]
By construction the planner only does collision checking and rejects a plan if there is a collision. The goal of pilz_industrial_motion is to get reproducible trajcetories.
Please also note that this repo is no longer maintained - the code moved into the moveit upstream repository.
