### ISSUE TITLE
Issue using pilz industrial motion planner after its merge into moveit-master

### ISSUE THREAD

**Issue by srujan-aris** [PilzDE/pilz_industrial_motion#337]
I observed an issue using the pilz_industrial_motion_planner after the merge into moveit-master, although I am not sure if this is intentional as I am a relatively noob software deveoper. I opened this bug report if someone noob like me is wondering what the reason behind it.

I am using ROS-noetic on my machine, earlier to the pilz_industrial_motion_planner's merge into moveit-master, I used  pilz_industrial_motion_planner built using an under-layed workspace with moveit-melodic installed from source. I had to mention 
`<arg name="planning_plugin" value="pilz::CommandPlanner" />` in `pilz_command_planner_planning_pipeline.launch.xml` file in my moveit_config_package. 

After the merge into moveit-master, I created a new workspace source-installed with moveit-master, I expected my moveit-config to work as is but the environment fails to use the pilz_industrial_motion_planner. I had to change 
`<arg name="planning_plugin" value="pilz::CommandPlanner" />` to 
`  <arg name="planning_plugin" value="pilz_industrial_motion_planner::CommandPlanner" />` 
 in `pilz_command_planner_planning_pipeline.launch.xml` to make it work normally.

**Comment by jschleicher** [comment]
Yes, that's expected. Thanks for writing this down for other people coming across the same issue! 👍 

 Closing.
