### ISSUE TITLE
Set default "Simple Command Planner" for moveit plugin

### ISSUE THREAD

**Issue by fmros** [PilzDE/pilz_industrial_motion#344]
I would like to set the "PTP" planner as default planner in the moveit configs. Elsewhere I have to select the planner everytime manually in the following tab of the rviz moveit plugin:

![image](https://user-images.githubusercontent.com/50864015/120599806-40df5680-c448-11eb-84e4-d61a3423cf02.png)

Is there a parameter that can be set in the moveit configs? 

Thanks

**Comment by martiniil** [comment]
Development of the planner is continued in MoveIt: https://github.com/ros-planning/moveit.
