### ISSUE TITLE
Multiple robot planning

### ISSUE THREAD

**Issue by KevinGalassi** [PilzDE/pilz_industrial_motion#355]
Hi,
I'm succesfully able to move a robot with moveit and pilz pipeline, but what if i have to plan the motion of  multiple robot? Because a can launch moveit in a namespace to differentiate the robot, but when in comes to use pilz API defining robot how can i pass the namespace of the robot to control?

In my specific case i have two robots "left" and "right" that have to move for an assembly task.

Thank your for the attention

**Comment by ct2034** [comment]
Hi Kevin. You can pass a planning goup to the commands with the `planning_group` param. For example for Ptp: 
`Ptp(planning_group="my_group", goal=[0.1, 0, 0, 0, 0, 0])`
