### ISSUE TITLE
Potential memory leak in path_circle_generator

### ISSUE THREAD

**Issue by agutenkunst** [PilzDE/pilz_industrial_motion#99]
https://github.com/PilzDE/pilz_industrial_motion/blob/1657377f87f524401c6b7d2228bd39e9a037043d/pilz_trajectory_generation/src/path_circle_generator.cpp#L42-L58

and

https://github.com/PilzDE/pilz_industrial_motion/blob/1657377f87f524401c6b7d2228bd39e9a037043d/pilz_trajectory_generation/src/path_circle_generator.cpp#L94-L110

look like they could leak...

**Comment by martiniil** [comment]
https://help.github.com/en/articles/closing-issues-using-keywords
